name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - run: flutter doctor

      - run: flutter pub get

      - run: flutter config --enable-windows-desktop

      - run: dart run build_runner build --delete-conflicting-outputs

      - run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: offline_era_windows
          path: build/windows/x64/runner/Release/
